package com.gl.StudentManagement.service;

import com.gl.StudentManagement.entity.Student;
import com.gl.StudentManagement.repository.StudentRepository;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import java.util.List;

@Service // This means that this class is a service
public class StudentService {
	@Autowired

	// This means to get the bean which is auto-generated by Spring
	// We will use it to handle the data

	StudentRepository studentRepository;

	// get all students

	public List<Student> findAll() {
		List<Student> students = studentRepository.findAll();
		return students;
	}

	// get student by id
	public Student findById(int theId) {
		// find an student by id
		return studentRepository.findById(theId).get();
	}

	// save an student

	public void save(Student theStudent) {
		// save student data to database
		studentRepository.save(theStudent);

	}

	// delete student by id
	public void deleteById(int theId) {

		// delete an student who has the id from the database

		studentRepository.deleteById(theId);
	}

}
